### ISSUE TITLE
transfer ownership

### ISSUE THREAD

**Issue by acxz** [ros-melodic-arch/ros-build-tools#1]
@bionade24 since I am a bit more active and would also like to add ROS 2 support to these set of scripts, I was wondering if you could tranfer ownership of this package to me?

**Comment by bionade24** [comment]
Sorry for not responding, but I still see the same problem as before. It's bad if we break kinectic, that's why I created `ros-build-tools-py3`.  If you can propose me as solution to the kinetic problem, otherwise I can't see a reason why it's that bad to use `ros-build-tools-py3`

**Comment by bionade24** [comment]
https://github.com/ros-melodic-arch/ros-build-tools/issues/1

**Comment by acxz** [comment]
I agree that its not 'that' bad to use `ros-build-tools-py3` but the version that most people use should be under `ros-build-tools`. If kinetic users want to use an older set of ros-build-tools they can use a version called `ros-build-tools-py2`. I could create a `ros-build-tools-py2` package and then we can update `ros-build-tools` with the never set of scripts.

**Comment by bionade24** [comment]
The problem is that the dep of `ros-kinetic-catkin` is `ros-build-tools`.  So we would nee to change that, create another package. At lot of work for nothing. I currently test if Kinetic even still builds otherwise I'll make a deletion request.

**Comment by bionade24** [comment]
Ok, doesn't even build. I'll start a deletion request for jade and kinetic and orphan the package.

**Comment by acxz** [comment]
> The problem is that the dep of ros-kinetic-catkin is ros-build-tools. So we would nee to change that, create another package. 

In the new `ros-build-tools-py2` package I can set `provides=(ros-build-tools)` to address this.

Thx for checking that `kinetic` doesn't even build.

**Comment by acxz** [comment]
Thx for transferring the package!
